/**
 * Extension message protocol (content ↔ SW ↔ popup/options).
 *
 * Translation I/O (do not confuse):
 * - TRANSLATE_TEXT / TRANSLATE_TEXT_RESULT — single page element (content script)
 * - TRANSLATE_TEXT_BATCH / TRANSLATE_TEXT_BATCH_RESULT — AI page-element batch (content)
 * - TRANSLATE_BATCH — fire-and-return batch for selection / subtitle / quick-action (no element map)
 * - TRANSLATE_INPUT_TEXT — input-box helper (legacy camelCase wire value; keep stable)
 *
 * Display mode:
 * - TOGGLE_DISPLAY_MODE — popup/command → SW (may inject scripts)
 * - UPDATE_DISPLAY_MODE — SW → content (reskin strategies)
 */
export const MESSAGE_TYPES = Object.freeze({
    CLEAR_CACHE: 'CLEAR_CACHE',
    CONVERSE_WITH_AI: 'CONVERSE_WITH_AI',
    DELETE_CLOUD_BACKUP: 'DELETE_CLOUD_BACKUP',
    DISPLAY_SELECTION_TRANSLATION: 'DISPLAY_SELECTION_TRANSLATION',
    DOWNLOAD_SETTINGS_FROM_CLOUD: 'DOWNLOAD_SETTINGS_FROM_CLOUD',
    GET_CACHE_INFO: 'GET_CACHE_INFO',
    GET_CLOUD_BACKUPS: 'GET_CLOUD_BACKUPS',
    GET_EFFECTIVE_SETTINGS: 'GET_EFFECTIVE_SETTINGS',
    GET_PROVIDER_HEALTH: 'GET_PROVIDER_HEALTH',
    GET_TRANSLATION_HISTORY: 'GET_TRANSLATION_HISTORY',
    /** Prefer sender.tab.id; kept for non-tab callers / diagnostics. */
    GET_TAB_ID: 'GET_TAB_ID',
    GET_VALIDATED_SETTINGS: 'GET_VALIDATED_SETTINGS',
    INFER_SUGGESTIONS: 'INFER_SUGGESTIONS',
    PING: 'PING',
    RELOAD_TRANSLATION_JOB: 'RELOAD_TRANSLATION_JOB',
    REQUEST_SUBTITLE_TRANSLATION_STATUS: 'REQUEST_SUBTITLE_TRANSLATION_STATUS',
    REQUEST_TRANSLATION_STATUS: 'REQUEST_TRANSLATION_STATUS',
    REVERT_PAGE_TRANSLATION: 'REVERT_PAGE_TRANSLATION',
    SAVE_RULE_CHANGE: 'SAVE_RULE_CHANGE',
    SETTINGS_UPDATED: 'SETTINGS_UPDATED',
    STOP_TRANSLATION: 'STOP_TRANSLATION',
    SUMMARIZE_CONTENT: 'SUMMARIZE_CONTENT',
    TEST_CONNECTION: 'TEST_CONNECTION',
    TEST_TRANSLATE_TEXT: 'TEST_TRANSLATE_TEXT',
    CLEAR_PROVIDER_HEALTH: 'CLEAR_PROVIDER_HEALTH',
    CLEAR_TRANSLATION_HISTORY: 'CLEAR_TRANSLATION_HISTORY',
    TOGGLE_DISPLAY_MODE: 'TOGGLE_DISPLAY_MODE',
    TOGGLE_SUBTITLE_TRANSLATION: 'TOGGLE_SUBTITLE_TRANSLATION',
    TOGGLE_SUMMARY_REQUEST: 'TOGGLE_SUMMARY_REQUEST',
    TOGGLE_TRANSLATION_REQUEST: 'TOGGLE_TRANSLATION_REQUEST',
    TOGGLE_TRANSLATION_REQUEST_AT_CONTENT: 'TOGGLE_TRANSLATION_REQUEST_AT_CONTENT',
    TRANSLATE_BATCH: 'TRANSLATE_BATCH',
    /** SW → content: run shared selection translate path (context menu / shortcut). */
    TRANSLATE_SELECTION_REQUEST: 'TRANSLATE_SELECTION_REQUEST',
    TRANSLATE_INPUT_TEXT: 'translateInputText',
    TRANSLATE_PAGE_REQUEST: 'TRANSLATE_PAGE_REQUEST',
    TRANSLATE_TEXT: 'TRANSLATE_TEXT',
    TRANSLATE_TEXT_BATCH: 'TRANSLATE_TEXT_BATCH',
    TRANSLATE_TEXT_BATCH_RESULT: 'TRANSLATE_TEXT_BATCH_RESULT',
    TRANSLATE_TEXT_RESULT: 'TRANSLATE_TEXT_RESULT',
    TRANSLATION_RETRY_SCHEDULED: 'TRANSLATION_RETRY_SCHEDULED',
    TRANSLATION_STATUS_UPDATE: 'TRANSLATION_STATUS_UPDATE',
    UPDATE_DISPLAY_MODE: 'UPDATE_DISPLAY_MODE',
    UPDATE_SUBTITLE_TRANSLATION_STATUS: 'UPDATE_SUBTITLE_TRANSLATION_STATUS',
    UPLOAD_SETTINGS_TO_CLOUD: 'UPLOAD_SETTINGS_TO_CLOUD',
});
